version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: mentoriza-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
